import { Product } from '@/types/product.types';

export const mockProducts: Product[] = [
    // --- MOBILES (5) ---
    {
        id: '1',
        slug: 'iphone-15-pro-max',
        name: 'iPhone 15 Pro Max',
        description: 'The ultimate iPhone with titanium design and A17 Pro chip.',
        price: 159900,
        originalPrice: 159900,
        discount: 0,
        category: 'mobiles',
        brand: 'Apple',
        images: ['https://i.pinimg.com/1200x/18/84/24/1884248df0286062436ea23d29ef5183.jpg'],
        rating: 4.8,
        reviewCount: 1240,
        inStock: true,
        specifications: { 'Processor': 'A17 Pro', 'Screen': '6.7 inch OLED' },
        features: ['Titanium design', 'A17 Pro chip', '48MP Main camera'],
        tags: ['smartphone', 'apple', 'premium'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '2',
        slug: 'samsung-galaxy-s24-ultra',
        name: 'Samsung Galaxy S24 Ultra',
        description: 'Galaxy AI is here. Welcome to the era of mobile AI.',
        price: 129999,
        originalPrice: 144999,
        discount: 10,
        category: 'mobiles',
        brand: 'Samsung',
        images: ['https://i.pinimg.com/736x/1e/3c/13/1e3c13955d4a14b23a3e2ad12271dd97.jpg'],
        rating: 4.7,
        reviewCount: 850,
        inStock: true,
        specifications: { 'Processor': 'Snapdragon 8 Gen 3', 'Screen': '6.8 inch AMOLED' },
        features: ['Galaxy AI', '200MP camera', 'S Pen included'],
        tags: ['smartphone', 'android', 'ai'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '3',
        slug: 'pixel-8-pro',
        name: 'Google Pixel 8 Pro',
        description: 'The most advanced Pixel camera and Google AI.',
        price: 99999,
        originalPrice: 106999,
        discount: 7,
        category: 'mobiles',
        brand: 'Google',
        images: ['https://i.pinimg.com/736x/a6/15/e2/a615e2e32f09decec12719223606b6ba.jpg'],
        rating: 4.6,
        reviewCount: 420,
        inStock: true,
        specifications: { 'Processor': 'Tensor G3', 'Screen': '6.7 inch OLED' },
        features: ['Tensor G3', 'Best Take', 'Magic Editor'],
        tags: ['smartphone', 'android', 'camera'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '4',
        slug: 'oneplus-12',
        name: 'OnePlus 12',
        description: 'Smooth Beyond Belief with Snapdragon 8 Gen 3.',
        price: 64999,
        originalPrice: 69999,
        discount: 7,
        category: 'mobiles',
        brand: 'OnePlus',
        images: ['https://i.pinimg.com/736x/09/26/d2/0926d2846a283d22da8066fc737567d3.jpg'],
        rating: 4.5,
        reviewCount: 310,
        inStock: true,
        specifications: { 'Processor': 'Snapdragon 8 Gen 3', 'Charging': '100W' },
        features: ['Snapdragon 8 Gen 3', '2K 120Hz ProXDR', '100W charging'],
        tags: ['smartphone', 'android', 'flagship-killer'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '5',
        slug: 'nothing-phone-2',
        name: 'Nothing Phone (2)',
        description: 'New Glyph Interface. OS 2.0. Snapdragon 8+ Gen 1.',
        price: 39999,
        originalPrice: 44999,
        discount: 11,
        category: 'mobiles',
        brand: 'Nothing',
        images: ['https://i.pinimg.com/1200x/19/b4/6d/19b46d392f9539aeff759fa3941abc94.jpg'],
        rating: 4.4,
        reviewCount: 215,
        inStock: true,
        specifications: { 'Processor': 'Snapdragon 8+ Gen 1', 'Interface': 'Glyph' },
        features: ['Glyph Interface', 'Nothing OS', 'Dual 50MP sensors'],
        tags: ['smartphone', 'android', 'design'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },

    // --- LAPTOPS (5) ---
    {
        id: '6',
        slug: 'macbook-pro-14-m3',
        name: 'MacBook Pro 14"',
        description: 'Mind-blowing. Head-turning. M3 chip.',
        price: 169900,
        originalPrice: 169900,
        discount: 0,
        category: 'laptops',
        brand: 'Apple',
        images: ['https://i.pinimg.com/1200x/18/30/7d/18307dfde0f655618d822607bda8c931.jpg'],
        rating: 4.9,
        reviewCount: 540,
        inStock: true,
        specifications: { 'Processor': 'M3', 'RAM': '8GB' },
        features: ['M3 chip', 'Liquid Retina XDR', '22hr battery'],
        tags: ['laptop', 'apple', 'pro'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '7',
        slug: 'dell-xps-15',
        name: 'Dell XPS 15',
        description: 'Immersive display and powerful performance for creators.',
        price: 145990,
        originalPrice: 160000,
        discount: 9,
        category: 'laptops',
        brand: 'Dell',
        images: ['https://i.pinimg.com/1200x/96/b8/19/96b819a2057454cd507198c2a60557e3.jpg'],
        rating: 4.7,
        reviewCount: 320,
        inStock: true,
        specifications: { 'Processor': 'Intel i9', 'GPU': 'RTX 4050' },
        features: ['OLED 3.5K', 'i9 Processor', 'NVIDIA RTX'],
        tags: ['laptop', 'windows', 'creator'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '8',
        slug: 'rog-zephyrus-g14',
        name: 'ASUS ROG Zephyrus G14',
        description: 'The world\'s most powerful 14-inch gaming laptop.',
        price: 139990,
        originalPrice: 154990,
        discount: 10,
        category: 'laptops',
        brand: 'ASUS',
        images: ['https://i.pinimg.com/1200x/b2/08/83/b20883b7dffe440e2e4118cbe0366b25.jpg'],
        rating: 4.8,
        reviewCount: 450,
        inStock: true,
        specifications: { 'Processor': 'Ryzen 9', 'GPU': 'RTX 4060' },
        features: ['AniMe Matrix', 'Ryzen 9', 'RTX 4060'],
        tags: ['laptop', 'gaming', 'windows'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '9',
        slug: 'macbook-air-15',
        name: 'MacBook Air 15"',
        description: 'Impressively big. Impossibly thin.',
        price: 134900,
        originalPrice: 134900,
        discount: 0,
        category: 'laptops',
        brand: 'Apple',
        images: ['https://i.pinimg.com/1200x/af/1d/d4/af1dd41ca103610a346c754f90c861f6.jpg'],
        rating: 4.8,
        reviewCount: 600,
        inStock: true,
        specifications: { 'Processor': 'M2', 'Screen': '15.3 inch' },
        features: ['M2 chip', '15.3-inch Liquid Retina', 'Silent design'],
        tags: ['laptop', 'apple', 'student'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '10',
        slug: 'hp-spectre-x360',
        name: 'HP Spectre x360',
        description: 'Craftsmanship meets power. 2-in-1 design.',
        price: 119999,
        originalPrice: 135000,
        discount: 11,
        category: 'laptops',
        brand: 'HP',
        images: ['https://i.pinimg.com/1200x/b1/d1/59/b1d1590b13f7ef7a22824faee4304e4e.jpg'],
        rating: 4.6,
        reviewCount: 280,
        inStock: true,
        specifications: { 'Processor': 'Intel Core Ultra', 'Type': '2-in-1' },
        features: ['OLED Touch', '360 Hinge', 'AI Camera'],
        tags: ['laptop', 'windows', 'convertible'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },

    // --- EARPHONES (6) ---
    {
        id: '11',
        slug: 'sony-wh-1000xm5',
        name: 'Sony WH-1000XM5',
        description: 'Industry-leading noise cancellation.',
        price: 26990,
        originalPrice: 34990,
        discount: 23,
        category: 'earphones',
        brand: 'Sony',
        images: ['https://i.pinimg.com/736x/3a/24/ab/3a24ab2b54c1c982b08f10fb010ce4f2.jpg'],
        rating: 4.6,
        reviewCount: 2300,
        inStock: true,
        specifications: { 'Battery': '30 hours', 'Type': 'Over-ear' },
        features: ['Auto NC Optimizer', '30hr battery', 'Multipoint connection'],
        tags: ['headphones', 'audio', 'sony'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '12',
        slug: 'airpods-pro-2',
        name: 'AirPods Pro (2nd Gen)',
        description: 'Magic like you’ve never heard.',
        price: 24900,
        originalPrice: 26900,
        discount: 7,
        category: 'earphones',
        brand: 'Apple',
        images: ['https://i.pinimg.com/1200x/03/40/1a/03401aab308f0567621159f808edc743.jpg'],
        rating: 4.8,
        reviewCount: 3500,
        inStock: true,
        specifications: { 'Chip': 'H2', 'Type': 'In-ear' },
        features: ['H2 chip', '2x Noise Cancellation', 'USB-C Case'],
        tags: ['earbuds', 'apple', 'wireless'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '13',
        slug: 'galaxy-buds2-pro',
        name: 'Samsung Galaxy Buds2 Pro',
        description: '24-bit Hi-Fi audio for diverse listening.',
        price: 16999,
        originalPrice: 19999,
        discount: 15,
        category: 'earphones',
        brand: 'Samsung',
        images: ['https://i.pinimg.com/736x/42/69/84/42698430fe420bb54aaabd35036cadad.jpg'],
        rating: 4.5,
        reviewCount: 1200,
        inStock: true,
        specifications: { 'Audio': '24-bit Hi-Fi', 'Type': 'In-ear' },
        features: ['24-bit Hi-Fi', 'ANC', '360 Audio'],
        tags: ['earbuds', 'samsung', 'android'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '14',
        slug: 'bose-quietcomfort-ultra',
        name: 'Bose QuietComfort Ultra',
        description: 'World-class noise cancellation, quieter than ever before.',
        price: 29900,
        originalPrice: 35900,
        discount: 17,
        category: 'earphones',
        brand: 'Bose',
        images: ['https://i.pinimg.com/736x/b3/0f/64/b30f64984fd5391040a1a38b0a866a59.jpg'],
        rating: 4.7,
        reviewCount: 890,
        inStock: true,
        specifications: { 'Battery': '24 hours', 'Type': 'Over-ear' },
        features: ['Immersive Audio', 'CustomTune', '24hr battery'],
        tags: ['headphones', 'audio', 'travel'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '15',
        slug: 'nothing-ear-2',
        name: 'Nothing Ear',
        description: 'Mighty little things. Ultra light.',
        price: 8999,
        originalPrice: 9999,
        discount: 10,
        category: 'earphones',
        brand: 'Nothing',
        images: ['https://i.pinimg.com/736x/96/a4/0e/96a40e6f34c28d8bd6fdaa054c857da4.jpg'],
        rating: 4.4,
        reviewCount: 670,
        inStock: true,
        specifications: { 'Codec': 'LHDC 5.0', 'Type': 'In-ear' },
        features: ['Personalized ANC', 'LHDC 5.0', 'Dual Connection'],
        tags: ['earbuds', 'nothing', 'design'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '16',
        slug: 'boat-rockerz-450',
        name: 'boAt Rockerz 450',
        description: 'Luscious Black, comfortable fit.',
        price: 1499,
        originalPrice: 3990,
        discount: 62,
        category: 'earphones',
        brand: 'boAt',
        images: ['https://i.pinimg.com/736x/3c/6a/b8/3c6ab871a0d4aa9559161064dd3dc66c.jpg'],
        rating: 4.2,
        reviewCount: 5000,
        inStock: true,
        specifications: { 'Playback': '15 hours', 'Type': 'On-ear' },
        features: ['15hr Playback', '40mm Drivers', 'Bluetooth 5.0'],
        tags: ['headphones', 'budget', 'bass'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];
